# Generated by Django 3.2.25 on 2024-03-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='events/images/', verbose_name='Изображение')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('postcode', models.CharField(max_length=150, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EventOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizations', to='api.event', verbose_name='Мероприятие')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_events', to='api.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Мероприятие организации',
                'verbose_name_plural': 'Мероприятия организаций',
                'ordering': ('event', 'organization'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(through='api.EventOrganization', to='api.Organization', verbose_name='Организация'),
        ),
        migrations.AddConstraint(
            model_name='eventorganization',
            constraint=models.UniqueConstraint(fields=('event', 'organization'), name='unique_event_organization'),
        ),
    ]
